version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: frenchdb
      MYSQL_USER: frenchuser
      MYSQL_PASSWORD: frenchpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # MODIFICATION ICI : on pointe vers l'image versionnée
    image: rolandmerhej1/french-app:v1.1
    # On retire 'build: .' car on utilise maintenant l'image du hub
    container_name: french-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/frenchdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: frenchuser
      SPRING_DATASOURCE_PASSWORD: frenchpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads/images

volumes:
  mysql-data: